name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please do not submit feature requests or ask for help on how to configure Vaultwarden here.

        The [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussions/) has sections for Questions and Ideas.

        Also, make sure you are running the [Latest Release](https://github.com/dani-garcia/vaultwarden/releases) of Vaultwarden!
        And search for existing open or closed issues or discussions regarding your topic before posting.
  - type: textarea
    id: support-string
    attributes:
      label: Vaultwarden Support String
      description: Output of the **Generate Support String** from the `/admin/diagnostics` page.
      placeholder: |
        1. Go to the Vaultwarden Admin of your instance https://example.domain.tld/admin/diagnostics
        2. Click on `Generate Support String`
        3. Click on `Copy To Clipboard`
        4. Replace this text by pasting it into this textarea without any modifications
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: How can we reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Click on '...'
        5. Etc '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: A clear and concise description of what is happening.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots and/or a short video to help explain your problem.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Provide the logs generated by Vaultwarden generated during the time this issue occurs.
      render: text
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
  - type: dropdown
    id: os
    attributes:
      label: Host/Server Operating System
      description: On what operating system are running the Vaultwarden server?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Android
        - Other
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What version of the operating system(s) are you seeing the problem on?
      placeholder: ex. Arch Linux, Ubuntu 24.04, Windows 11
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment method
      description: How did you deployed Vaultwarden?
      multiple: false
      options:
        - Official Container Image
        - Build from source
        - OS Package (apt, yum/dnf, pacman, apk, nix, ...)
        - Manually Extracted from Container Image
        - Downloaded from GitHub Actions Release Workflow
        - Other method
    validations:
      required: true
  - type: textarea
    id: deployment-other
    attributes:
      label: Custom deployment method
      description: If you deployed Vaultwarden via any other method, please describe how.
  - type: input
    id: version
    attributes:
      label: Vaultwarden Build Version
      description: What version of Vaultwarden are you running?
      placeholder: ex. v1.31.0 or v1.32.0-3466a804
    validations:
      required: true
  - type: dropdown
    id: clients
    attributes:
      label: Clients
      description: What client(s) are you seeing the problem on?
      multiple: true
      options:
        - Web Vault
        - Browser Extension
        - CLI
        - Desktop
        - Android
        - iOS
    validations:
      required: true
  - type: input
    id: client-version
    attributes:
      label: Client Version
      description: What version(s) of the client(s) are you seeing the problem on?
      placeholder: ex. v2024.7.2
