name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  #
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please *do not* submit feature requests or ask for help on how to configure Vaultwarden here.

        The [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussions/) has sections for Questions and Ideas.

        Also, make sure you are running [![GitHub Release](https://img.shields.io/github/release/dani-garcia/vaultwarden.svg)](https://github.com/dani-garcia/vaultwarden/releases/latest) of Vaultwarden!
        And search for existing open or closed issues or discussions regarding your topic before posting.

        Be sure to check and validate the Vaultwarden Admin Diagnostics (`/admin/diagnostics`) page for any errors!
        See here [how to enable the admin page](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page).
  #
  - id: support-string
    type: textarea
    attributes:
      label: Vaultwarden Support String
      description: Output of the **Generate Support String** from the `/admin/diagnostics` page.
      placeholder: |
        1. Go to the Vaultwarden Admin of your instance https://example.domain.tld/admin/diagnostics
        2. Click on `Generate Support String`
        3. Click on `Copy To Clipboard`
        4. Replace this text by pasting it into this textarea without any modifications
    validations:
      required: true
  #
  - id: version
    type: input
    attributes:
      label: Vaultwarden Build Version
      description: What version of Vaultwarden are you running?
      placeholder: ex. v1.31.0 or v1.32.0-3466a804
    validations:
      required: true
  #
  - id: deployment
    type: dropdown
    attributes:
      label: Deployment method
      description: How did you deploy Vaultwarden?
      multiple: false
      options:
        - Official Container Image
        - Build from source
        - OS Package (apt, yum/dnf, pacman, apk, nix, ...)
        - Manually Extracted from Container Image
        - Downloaded from GitHub Actions Release Workflow
        - Other method
    validations:
      required: true
  #
  - id: deployment-other
    type: textarea
    attributes:
      label: Custom deployment method
      description: If you deployed Vaultwarden via any other method, please describe how.
  #
  - id: reverse-proxy
    type: input
    attributes:
      label: Reverse Proxy
      description: Are you using a reverse proxy, if so which and what version?
      placeholder: ex. nginx 1.26.2, caddy 2.8.4, traefik 3.1.2, haproxy 3.0
    validations:
      required: true
  #
  - id: os
    type: dropdown
    attributes:
      label: Host/Server Operating System
      description: On what operating system are you running the Vaultwarden server?
      multiple: false
      options:
        - Linux
        - NAS/SAN
        - Cloud
        - Windows
        - macOS
        - Other
    validations:
      required: true
  #
  - id: os-version
    type: input
    attributes:
      label: Operating System Version
      description: What version of the operating system(s) are you seeing the problem on?
      placeholder: ex. Arch Linux, Ubuntu 24.04, Kubernetes, Synology DSM 7.x, Windows 11
  #
  - id: clients
    type: dropdown
    attributes:
      label: Clients
      description: What client(s) are you seeing the problem on?
      multiple: true
      options:
        - Web Vault
        - Browser Extension
        - CLI
        - Desktop
        - Android
        - iOS
    validations:
      required: true
  #
  - id: client-version
    type: input
    attributes:
      label: Client Version
      description: What version(s) of the client(s) are you seeing the problem on?
      placeholder: ex. CLI v2024.7.2, Firefox 130 - v2024.7.0
  #
  - id: reproduce
    type: textarea
    attributes:
      label: Steps To Reproduce
      description: How can we reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Click on '...'
        5. Etc '...'
    validations:
      required: true
  #
  - id: expected
    type: textarea
    attributes:
      label: Expected Result
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  #
  - id: actual
    type: textarea
    attributes:
      label: Actual Result
      description: A clear and concise description of what is happening.
    validations:
      required: true
  #
  - id: logs
    type: textarea
    attributes:
      label: Logs
      description: Provide the logs generated by Vaultwarden during the time this issue occurs.
      render: text
  #
  - id: screenshots
    type: textarea
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots and/or a short video to help explain your problem.
  #
  - id: additional-context
    type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
