use std::{
    collections::HashMap,
    sync::{Arc, LazyLock, Mutex},
    time::Duration,
};

use diesel::ConnectionError;
use url::Url;

// Generate a Postgres libpq connection string. The input connection string has
// the following format:
//
// dsql://<dsql-id>.dsql.<aws-region>.on.aws
//
// The generated connection string has the form:
//
// postgresql://<dsql-id>.dsql.<aws-region>.on.aws/postgres?sslmode=require&user=admin&password=<auth-token>
//
// The auth token is generated by the AWS SDK for DSQL and is valid for up to
// 15 minutes. Cache each unique DSQL URL for 14 minutes to avoid regenerating
// a token for every pooled connection.
pub(crate) fn psql_url(url: &str) -> Result<String, ConnectionError> {
    struct PsqlUrl {
        timestamp: std::time::Instant,
        url: String,
    }

    static PSQL_URLS: LazyLock<Mutex<HashMap<String, Arc<Mutex<Option<PsqlUrl>>>>>> =
        LazyLock::new(|| Mutex::new(HashMap::new()));

    let mut psql_urls =
        PSQL_URLS.lock().map_err(|e| ConnectionError::BadConnection(format!("Failed to lock DSQL URLs: {e}")))?;

    let psql_url_lock = if let Some(existing_psql_url_lock) = psql_urls.get(url) {
        existing_psql_url_lock.clone()
    } else {
        let psql_url_lock = Arc::new(Mutex::new(None));
        psql_urls.insert(url.to_string(), psql_url_lock.clone());
        psql_url_lock
    };

    let mut psql_url_lock_guard =
        psql_url_lock.lock().map_err(|e| ConnectionError::BadConnection(format!("Failed to lock DSQL URL: {e}")))?;

    drop(psql_urls);

    if let Some(ref psql_url) = *psql_url_lock_guard {
        if psql_url.timestamp.elapsed() < Duration::from_secs(14 * 60) {
            debug!("Reusing DSQL auth token for connection '{url}'");
            return Ok(psql_url.url.clone());
        }

        info!("Refreshing DSQL auth token for connection '{url}'");
    } else {
        info!("Generating new DSQL auth token for connection '{url}'");
    }

    let mut psql_url = Url::parse(url).map_err(|e| ConnectionError::InvalidConnectionUrl(e.to_string()))?;

    let host = psql_url
        .host_str()
        .ok_or_else(|| ConnectionError::InvalidConnectionUrl("Missing hostname in DSQL URL".to_string()))?
        .to_string();

    static DSQL_REGION_FROM_HOST_RE: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"^[a-z0-9]+\.dsql\.(?P<region>[a-z0-9-]+)\.on\.aws$")
            .expect("Failed to compile DSQL region regex")
    });

    let region = DSQL_REGION_FROM_HOST_RE
        .captures(&host)
        .and_then(|captures| captures.name("region"))
        .ok_or_else(|| ConnectionError::InvalidConnectionUrl("Failed to find AWS region in DSQL hostname".to_string()))?
        .as_str()
        .to_string();

    let auth_config = aws_sdk_dsql::auth_token::Config::builder()
        .hostname(host)
        .region(aws_config::Region::new(region))
        .build()
        .map_err(|e| ConnectionError::BadConnection(format!("Failed to build DSQL auth token signer config: {e}")))?;

    let signer = aws_sdk_dsql::auth_token::AuthTokenGenerator::new(auth_config);
    let sdk_config = crate::aws::aws_sdk_config_blocking()
        .map_err(|e| ConnectionError::BadConnection(format!("Failed to load AWS SDK config: {e}")))?;
    let now = std::time::Instant::now();

    let auth_token = std::thread::spawn(move || {
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build()?;
        rt.block_on(signer.db_connect_admin_auth_token(sdk_config))
    })
    .join()
    .map_err(|e| ConnectionError::BadConnection(format!("Failed to generate DSQL auth token: {e:?}")))?
    .map_err(|e| ConnectionError::BadConnection(format!("Failed to generate DSQL auth token: {e}")))?;

    psql_url.set_scheme("postgresql").expect("Failed to set 'postgresql' as scheme for DSQL connection URL");
    psql_url.set_path("postgres");
    psql_url
        .query_pairs_mut()
        .append_pair("sslmode", "require")
        .append_pair("user", "admin")
        .append_pair("password", auth_token.as_str());

    psql_url_lock_guard.replace(PsqlUrl {
        timestamp: now,
        url: psql_url.to_string(),
    });

    Ok(psql_url.to_string())
}
