#!/usr/bin/env bash

set -ex

# If requested, print some environment info for troubleshooting.
if [[ -n "${DOCKER_HUB_DEBUG}" ]]; then
    id
    pwd
    df -h
    env
    docker info
    docker version
fi

# Install build dependencies.
deps=(
    jq
)
apt-get update
apt-get install -y "${deps[@]}"

# Docker Hub uses a shallow clone and doesn't fetch tags, which breaks some
# Git operations that we perform later, so fetch the complete history and
# tags first. Note that if the build is cached, the clone may have been
# unshallowed already; if so, unshallowing will fail, so skip it.
if [[ -f .git/shallow ]]; then
    git fetch --unshallow --tags
fi
