name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 3 * * THU"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync with Upstream
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@master

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@main
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: dani-garcia/vaultwarden
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false

      - name: Check for Failure
        if: failure()
        run: |
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
          exit 1
